#Site settings
title: Dattaraj's Blog
email: dattaraj@dattarajpai.com
description:  "Portfolio of Dattaraj Pai."
url: "http://www.dattarajpai.com" # the base hostname & protocol for your site
twitter_username: dattarajpai
github_username:  dattarajpai

# Build settings
markdown: kramdown





# Outputting
permalink:     none




