#Site settings
title: Dattaraj Pai
email: dattaraj@dattarajpai.com
description: > # this means to ignore newlines until "baseurl:"
url: "http://www.dattarajpai.com" # the base hostname & protocol for your site
twitter_username: dattarajpai
github_username:  dattarajpai

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

redirects: yes
